[package]
name = "slow-scan-print"
version = "0.3.0"
authors = ["Meow0x7E <Meow0x7E@outlook.com>"]
edition = "2024"
description = "Text is printed at fixed intervals by character or by line, and its name is inspired by SSTV (Slow Scan TV)."
license = "MIT"

[dependencies]
clap = { version = "4.5.7", features = ["unicode", "wrap_help", "cargo"] }
console = "0.15.8"
duration-str = "0.12.0"
rust-i18n = "3.1.2"
signal-hook = "0.3.17"
sys-locale = "0.3.2"

[profile.release]
strip = true
lto = true
codegen-units = 1
