unstable_features = true
edition = "2021"

max_width = 160
tab_spaces = 4

chain_width = 60

group_imports = "StdExternalCrate"
trailing_comma = "Never"
trailing_semicolon = true
fn_single_line = true
