edition = "2024"
enum_discrim_align_threshold = 20
fn_single_line = true
format_code_in_doc_comments = true
hex_literal_case = "Upper"
float_literal_trailing_zero = "IfNoPostfix"
imports_layout = "HorizontalVertical"
max_width = 80
imports_granularity = "Module"
newline_style = "Native"
group_imports = "StdExternalCrate"
tab_spaces = 4
trailing_comma = "Never"
unstable_features = true
use_field_init_shorthand = true
